### ISSUE TITLE
Link to flashing tool is dead

### ISSUE THREAD

**Issue by hobbit44** [smlight-dev/slzb-06-manual#1]
https://github.com/smlight-dev/slzb-06-manual/blob/main/docs/guide/flashing-and-updating/updating-cc2652p.md?plain=1#L16

**Comment by sergge1** [comment]
> https://github.com/smlight-dev/slzb-06-manual/blob/main/docs/guide/flashing-and-updating/updating-cc2652p.md?plain=1#L16

Corrected. thanks for reporting.
