### ISSUE TITLE
Please add mDNS to manual

### ISSUE THREAD

**Issue by Peter915671** [smlight-dev/slzb-06-manual#2]
Since SLZB-06 supports mDNS, it would be helpful to add to the manual that the adapter can be found with the address: slzb-06.local .

My router didn't show the device at all. So, how to connect without knowing the IP-address.

mDNS solves that issue perfectly.

**Comment by sergge1** [comment]
> Since SLZB-06 supports mDNS, it would be helpful to add to the manual that the adapter can be found with the address: slzb-06.local .
> 
> My router didn't show the device at all. So, how to connect without knowing the IP-address.
> 
> mDNS solves that issue perfectly.

That is a very very good point, added here https://github.com/smlight-dev/slzb-06-manual/commit/26202dabab640dfd325345f761ea16f51554d3b8; thank you for your comment. 
@Tarik2142  FYI
